#+title: defile.el - Embed IDs and tags in file names
#+author: Nick OBrien

Defile is a simple package for embedding IDs and tags in file names.
File names are formatted as follows, with =[]= indicating optional
fields:

#+begin_example
[ID--]TITLE[__TAG1_TAG2][.EXT]
#+end_example

The main benefits of this format are:

- An alternative to a directory hierarchy.  In many cases, it doesn't
  make sense to distinguish =tag1/tag2/file= from =tag2/tag1/file=.

- An unchanging ID for links, currently used by the "defile" Org link
  format.

Some unfortunate downsides are:

- File name lengths are limited, which also limits the amount of tags
  you can add.

- With a lot of tags, the file name becomes an eye-sore.

The main features Defile provides are:

- Renaming files with special completion (=defile-rename-file=,
  =defile-dired-do-rename=).

- A file for adding descriptions to tags, which are shown when
  completing a tag (=defile-tag-file=).

- Renaming a tag, which renames all files with that tag
  (=defile-rename-tags=).

- An Org link format "defile" (accessible from =org-store-link= and
  =org-insert-link=).

* Denote

Defile was largely inspired by [[https://protesilaos.com/emacs/denote][Denote]].  If you already have Denote,
then you probably won't gain much from Defile unless you want
arbitrary IDs (Denote only allows ISO 8601 timestamps as IDs).  If you
decide to use both, Defile works perfectly fine on top of Denote.  By
default, Defile uses a superset of Denote's file name format.  If you
include =denote-directory= in your =defile-lookup-path=, your Denote
notes will be included as Defile files.  For example, Defile tag
completions will include Denote tags.

* Installation

Using [[https://github.com/progfolio/elpaca][elpaca]] and =elpaca-use-package-mode=:

#+begin_src emacs-lisp :results none
(use-package defile
  :ensure ( defile :type git :host github
	    :repo "nick4f42/defile.el" :depth nil)
  :init
  (with-eval-after-load 'dired
    (add-hook 'dired-mode-hook #'defile-dired-mode))

  :config
  (setopt defile-lookup-path '("~/Documents")))
#+end_src
